name: Update Bookings

on:
  workflow_dispatch:
    inputs:
      name:
        description: '姓名'
        required: true
      start:
        description: '开始时间'
        required: true
      end:
        description: '结束时间'
        required: true

jobs:
  update-bookings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 更新 bookings.json
        run: |
          FILE="lab343-eeg/bookings.json"
          NEW='{"title":"${{ github.event.inputs.name }}","start":"${{ github.event.inputs.start }}","end":"${{ github.event.inputs.end }}","backgroundColor":"#cccccc","borderColor":"#cccccc"}'
          cat $FILE | jq ". + [$NEW]" > tmp.json
          mv tmp.json $FILE
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $FILE
          git commit -m "Add booking by ${{ github.event.inputs.name }}"
          git push
